//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginSystem.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoginSystem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been banned until: .
        /// </summary>
        internal static string ACCOUNT_BANNED {
            get {
                return ResourceManager.GetString("ACCOUNT_BANNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congrulations the account has been created..
        /// </summary>
        internal static string ACCOUNT_CREATED {
            get {
                return ResourceManager.GetString("ACCOUNT_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The E-Mail provided already is tied to an account..
        /// </summary>
        internal static string ACCOUNT_EMAIL_EXIST {
            get {
                return ResourceManager.GetString("ACCOUNT_EMAIL_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information provided does not match any of our records..
        /// </summary>
        internal static string ACCOUNT_INVALID {
            get {
                return ResourceManager.GetString("ACCOUNT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username you are trying to register has been taken..
        /// </summary>
        internal static string ACCOUNT_NAME_EXIST {
            get {
                return ResourceManager.GetString("ACCOUNT_NAME_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has not been activated just yet..
        /// </summary>
        internal static string ACCOUNT_NOT_ACTIVATED {
            get {
                return ResourceManager.GetString("ACCOUNT_NOT_ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email you have provided does not seem to be valid..
        /// </summary>
        internal static string INVALID_EMAIL {
            get {
                return ResourceManager.GetString("INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords do not match..
        /// </summary>
        internal static string PASSWORD_NO_MATCH {
            get {
                return ResourceManager.GetString("PASSWORD_NO_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Pauloruberto_Custom_Round_Yosemite_FileBot {
            get {
                object obj = ResourceManager.GetObject("Pauloruberto_Custom_Round_Yosemite_FileBot", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Pauloruberto_Custom_Round_Yosemite_FileMaker_Pro {
            get {
                object obj = ResourceManager.GetObject("Pauloruberto_Custom_Round_Yosemite_FileMaker_Pro", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Pauloruberto_Custom_Round_Yosemite_KeepassX {
            get {
                object obj = ResourceManager.GetObject("Pauloruberto_Custom_Round_Yosemite_KeepassX", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Pauloruberto_Custom_Round_Yosemite_PhpStorm {
            get {
                object obj = ResourceManager.GetObject("Pauloruberto_Custom_Round_Yosemite_PhpStorm", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There seems to be a problem on our end ;( .
        /// </summary>
        internal static string SERVER_ERROR {
            get {
                return ResourceManager.GetString("SERVER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That information you have entered is too short. It must be over three characters!.
        /// </summary>
        internal static string SHORT_DATA {
            get {
                return ResourceManager.GetString("SHORT_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has happened..
        /// </summary>
        internal static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
    }
}
